from odoo import fields, models,api,_
from odoo.exceptions import ValidationError
allowed_characters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r',
                      's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
                      'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '1', '2',
                      '3', '4', '5', '6', '7', '8', '9', '0', ' ']

class UtmCampaign(models.Model):
    _inherit = 'utm.campaign'

    receipt_amount = fields.Integer(default=0, compute="_compute_sale_receipt_amount", string="Revenues generated by the campaign")
    bu_community_id = fields.Many2one('bu_community',string="Community")

    @api.constrains('name')
    def _check_name(self):
        if any(name not in allowed_characters for name in self.name):
            raise ValidationError(_('Please enter valid name.not special character or other Language'))

    def _compute_sale_receipt_amount(self):
        for rec in self:
            rec.receipt_amount = 0
            receipts = receipt = self.env['lyg.account.receipt'].search([('utm_campaign_id', '=', self.id),('state', '=','post')]) 
            receipts_total = sum([receipt.total_pay_amount for receipt in receipts])
            rec.receipt_amount = receipts_total

    def action_redirect_to_receipt(self):
        action = self.env["ir.actions.actions"]._for_xml_id("lyg_receipt.action_account_receipt_form")
        receipt = self.env['lyg.account.receipt'].search([('utm_campaign_id', '=', self.id)])
        action['context'] = {
            'create': False,
            'edit': False,
            'view_no_maturity': True
        }
        action['domain'] = [
            ('id', 'in', receipt.ids),
            ('state', '=','post')
        ]
        return action