# -*- coding: utf-8 -*-
# Part of Creyox Technologies
{
    "name": " MRP Overhead Cost | Manufacturing Overhead Analysis |Manufacturing Overhead Expense |  Manufacturing Cost Management | MRP Operational Costs",
    "author": "Creyox Technologies",
    "website": "https://www.creyox.com",
    "support": "support@creyox.com",
    "version": "17.0.0.1",
    "summary": "The MRP Overhead Cost module automates the tracking and management of expenses incurred during the manufacturing process of products. It aims to streamline all overhead cost. ",
    "sequence": 10,
    "description": """
        This module is designed to automate and manage the various expenses that arise during the manufacturing of products. By integrating seamlessly with existing systems, it allows manufacturers to efficiently allocate overhead costs, ensuring accurate financial reporting and resource management. The module supports features like overhead master data management, production data tracking, and configuration settings, making it a comprehensive tool for any manufacturing business.,
        MRP Overhead Cost,
        Operational Overhead Expense,
        Manufacturing Overhead Expense,
        Standard Cost Allocation,
        Production Overhead Cost,
        Operational Expense Allocation,
        Manufacturing Cost Overhead,
        Standard Expense Distribution,
        Administrative Overhead Cost,
        Facility Overhead Expense,
        Cost Allocation Method,
        Operational Cost Management,
        Indirect Manufacturing Costs,
        Variable Cost Overhead
    """,
    "category": "Manufacturing",
    "price": "40",
    "currency": "USD",
    "license": "AGPL-3",
    "depends": ["base", "mrp", "account"],
    "data": [
        "security/ir.model.access.csv",
        "views/cr_overhead_master.xml",
        "views/mrp.xml",
        "views/cr_overhead_data.xml",
        "views/res_config_settings.xml",
        "views/mrp_production.xml",
        "views/cr_production_data.xml",
        "views/product_template.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
    "images": ["static/description/banner.png"],
}
