# -*- coding: utf-8 -*-
# Email: sales@creyox.com
{
    'name': "Planned Vs. Actual Consumption Report of MRP | Consumption Analysis in Manufacturing | Consumption Report",
    'version': '18.0',
    'summary': """Get the planned vs. actual consumption report.""",
    'category': "Manufacturing",
    'price': "30",
    'currency': "USD",
    'author': "Creyox Technologies",
    'sequence': 0,
    'description': """
        Planned Vs. Actual Consumption Report of MRP,
        Consumption Analysis in Manufacturing,
        Consumption Report,
        Planned Vs. Actual Consumption Report of MRP in Odoo,
        Consumption Analysis in Manufacturing in Odoo,
        Consumption Report in Odoo,
        Planned Vs. Actual Consumption Report of Manufacturing Order in Odoo,
        Planned Vs. Actual Consumption Report of Manufacturing Order,
        Planned Vs Actual Consumption in Odoo,
        Consumption Report of Manufacturing Order in Odoo,
        Consumption Report of Manufacturing Order,
        Detailed Consumption report of Manufacturing Order,
        Detailed Consumption report of Manufacturing Order in Odoo,
    """,
    'depends': ['mrp'],
    "license": "OPL-1",
    'data': [
        'security/ir.model.access.csv',
        'views/mrp_production_form_view.xml',
        'views/consumption_report_template.xml',
        'views/report.xml',
    ],
    'demo': [],
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
