# -*- coding: utf-8 -*-
# Part of Creyox Technologies.

{
    "name": "Invoice Partial Payment Reconciliation | Partial Payment Reconciliation | Invoice Payment Reconciliation | Customer Payment Reconciliation | Vendor Payment Reconciliation",
    "author": "Creyox Technologies",
    "website": "https://www.creyox.com",
    "support": "support@creyox.com",
    "category": "Accounting",
    "summary": """
    		 The Invoice Partial Payment Reconciliation Odoo app is a valuable tool for managing customer or vendor payments, 
                allowing users to register partial payments with write-offs and reconciliation. From the invoice screen, you can 
                select an existing payment and record a partial payment for the invoice, including the option for write-offs. 
                This module enables the creation of single or multiple invoices/bills for partial payments. Additionally, users 
                can easily view the remaining outstanding credit or debit amount for partially paid invoices.	
    		
    		 Payment Reconciliation,
    		 Payment Reconciliation in odoo,
                Partial Payment Reconciliation,
                Partial Customer Invoice Payment,
                Partial Vendor Bill Payment,
                Partial Account Payment Reconcilation,
                Customer Partial Payment Reconciliation,
                Vendor Partial Payment Reconciliation,
                Partial Invoice Payment Clearance,
                Partial Payment Reconcilation in odoo,
                Invoice Reconciliation with Partial Payment,
                Invoice-Bill Partial Payment Reconciliation,
                Partial Reconciliation and Payment for Single Customer Invoice,
                Partial Reconciliation and Payment for Multiple Customer Invoice,
                Partial Reconciliation and Payment for Single Vendor Bill,
                Partial Reconciliation and Payment for Multiple Vendor Bills,
                Partial Reconciliation for Customer Invoice,
                Partial Reconciliation for Vendor Bill,
                Partial Payment Reconciliation Process,
                Payment Reconciliation, 
                Reconciliation of Partial Payments,
                Partial Transaction Reconciliation,
                Installment Payment Reconciliation,
                Partial Amount Reconciliation,
                Split Payment Reconciliation,
                Partial Invoice Reconciliation,
                Partial Bill Reconcialation,
                Partial Balance Reconciliation,
                Reconciliation of Partially Settled Payments,
                Partial Payment Account Reconciliation,
                Reconciliation of Outstanding Partial Payments,
                Reconciliation for Partial Payments,
                Ongoing Payment Reconciliation,                
               """,
    "license": "OPL-1",
    "version": "18.0",
    "description": """
                    The Invoice Partial Payment Reconciliation Odoo app is a valuable tool for managing customer or vendor payments, 
                allowing users to register partial payments with write-offs and reconciliation. From the invoice screen, you can 
                select an existing payment and record a partial payment for the invoice, including the option for write-offs. 
                This module enables the creation of single or multiple invoices/bills for partial payments. Additionally, users 
                can easily view the remaining outstanding credit or debit amount for partially paid invoices.	
    		
    		 Payment Reconciliation,
    		 Payment Reconciliation in odoo,
                Partial Payment Reconciliation,
                Partial Customer Invoice Payment,
                Partial Vendor Bill Payment,
                Partial Account Payment Reconcilation,
                Customer Partial Payment Reconciliation,
                Vendor Partial Payment Reconciliation,
                Partial Invoice Payment Clearance,
                Partial Payment Reconcilation in odoo,
                Invoice Reconciliation with Partial Payment,
                Invoice-Bill Partial Payment Reconciliation,
                Partial Reconciliation and Payment for Single Customer Invoice,
                Partial Reconciliation and Payment for Multiple Customer Invoice,
                Partial Reconciliation and Payment for Single Vendor Bill,
                Partial Reconciliation and Payment for Multiple Vendor Bills,
                Partial Reconciliation for Customer Invoice,
                Partial Reconciliation for Vendor Bill,
                Partial Payment Reconciliation Process,
                Payment Reconciliation, 
                Reconciliation of Partial Payments,
                Partial Transaction Reconciliation,
                Installment Payment Reconciliation,
                Partial Amount Reconciliation,
                Split Payment Reconciliation,
                Partial Invoice Reconciliation,
                Partial Bill Reconcialation,
                Partial Balance Reconciliation,
                Reconciliation of Partially Settled Payments,
                Partial Payment Account Reconciliation,
                Reconciliation of Outstanding Partial Payments,
                Reconciliation for Partial Payments,
                Ongoing Payment Reconciliation,
    """,
    "depends": ["account", "base", "web"],
    "data": [
        "security/ir.model.access.csv",
        "wizard/payment_wizard_views.xml",
        "wizard/partial_payment_wizard_views.xml",
        "views/account_move_inherit_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "cr_partial_payment_reconciliation/static/src/js/custom_payment_field.js",
        ],
    },
    "installable": True,
    "auto_install": False,
    "application": True,
    "images": ["static/description/banner.png"],
    "price": "65",
    "currency": "USD",
}
