{
    "name": "Internal Website",
    "version": "16.0.0.3",
    "category": "Website",
    "summary": "Landing Page Block",
    "description": """""",
    "author": "Your Name / Creyox Technologies",
    "website": "https://creyoxtechnologies.com",
    "license": "LGPL-3",
    "depends": ["website", "contacts", "crm", "website_hr_recruitment","website_blog"],
    "data": [
        "security/ir.model.access.csv",
        'views/website_header.xml',
        'views/menus.xml',
        "views/cr_client.xml",
        "views/snippets.xml",
        "views/snippets/section1.xml",
        "views/snippets/section2.xml",
        "views/snippets/section3.xml",
        "views/snippets/section4.xml",
        "views/snippets/section5.xml",
        "views/snippets/section6.xml",
        "views/snippets/section7.xml",
        "views/snippets/about_us_snippet_section1.xml",
        "views/snippets/about_us_snippet_section2.xml",
        "views/snippets/about_us_snippet_section3.xml",
        "views/snippets/about_us_snippet_section4.xml",
        "views/snippets/about_us_snippet_section5.xml",
        "views/snippets/service1_erp_solution.xml",
        "views/snippets/service2_crm_solution.xml",
        "views/snippets/service3_pos_solution.xml",
        "views/snippets/service4_web_development.xml",
        "views/snippets/service5_odoo_development.xml",
        "views/snippets/service6_odoo_integration_solution.xml",
        "views/snippets/service7_odoo_implementation_solution.xml",
        "views/snippets/service8_odoo_customization_solution.xml",
        "views/snippets/service9_odoo_migration_solution.xml",
        "views/snippets/service10_odoo_support_solution.xml",
        "views/snippets/service11_odoo_consulting_solution.xml",
        "views/snippets/service12_odoo_training_solution.xml",
        "views/snippets/service13_sap_services_solution.xml",
        "views/snippets/career.xml",
        "views/snippets/odoo_cloud_management.xml",
        "views/footer.xml",
        "views/contact_us.xml",
        "views/website_hr_recruitment_templates.xml",
        'views/job_apply_template.xml',
        'views/case_study_data.xml',
        'views/snippets/case_study.xml',
        "views/case_study_main_template.xml",
        "views/login_page.xml",
        'views/forget_password.xml',
        'views/sign_up.xml',
        'views/hide_contactus.xml',
    ],
    'assets': {
        'website.assets_wysiwyg': [
            'cr_internal_website_theme/static/src/snippets/section6/options.js',
            'cr_internal_website_theme/static/src/snippets/case_study/options.js',
        ],
        'web.assets_frontend': [
            'cr_internal_website_theme/static/src/scss/header_style.scss',
            'cr_internal_website_theme/static/src/scss/section1.scss',
            'cr_internal_website_theme/static/src/scss/section2.scss',
            'cr_internal_website_theme/static/src/scss/section3.scss',
            'cr_internal_website_theme/static/src/scss/section4.scss',
            'cr_internal_website_theme/static/src/scss/section5.scss',
            'cr_internal_website_theme/static/src/scss/section6.scss',
            'cr_internal_website_theme/static/src/scss/section7.scss',
            'cr_internal_website_theme/static/src/scss/about_us_section1.scss',
            'cr_internal_website_theme/static/src/scss/about_us_section2.scss',
            'cr_internal_website_theme/static/src/scss/about_us_section3.scss',
            'cr_internal_website_theme/static/src/scss/about_us_section4.scss',
            'cr_internal_website_theme/static/src/scss/about_us_section5.scss',
            'cr_internal_website_theme/static/src/scss/service1_erp_solution.scss',
            'cr_internal_website_theme/static/src/scss/service2_crm_solution.scss',
            'cr_internal_website_theme/static/src/scss/service3_pos_solution.scss',
            'cr_internal_website_theme/static/src/scss/service4_web_dev_solution.scss',
            'cr_internal_website_theme/static/src/scss/service5_odoo_dev_solution.scss',
            'cr_internal_website_theme/static/src/scss/service6_odoo_integration_solution.scss',
            'cr_internal_website_theme/static/src/scss/service7_odoo_implementation_solution.scss',
            'cr_internal_website_theme/static/src/scss/service8_odoo_customization_solution.scss',
            'cr_internal_website_theme/static/src/scss/service9_odoo_migration_solution.scss',
            'cr_internal_website_theme/static/src/scss/service10_odoo_support_solution.scss',
            'cr_internal_website_theme/static/src/scss/service11_odoo_consulting_solution.scss',
            'cr_internal_website_theme/static/src/scss/service12_odoo_training_solution.scss',
            'cr_internal_website_theme/static/src/scss/service13_sap_services_solution.scss',
            'cr_internal_website_theme/static/src/scss/footer_custom.scss',
            'cr_internal_website_theme/static/src/scss/contact_us.scss',
            'cr_internal_website_theme/static/src/scss/career.scss',
            'cr_internal_website_theme/static/src/scss/website_hr_recruitment_templates.scss',
            'cr_internal_website_theme/static/src/scss/job_apply.scss',
            'cr_internal_website_theme/static/src/scss/case_study.scss',
            'cr_internal_website_theme/static/src/scss/login_page.scss',
            'cr_internal_website_theme/static/src/scss/forget_password.scss',
            'cr_internal_website_theme/static/src/scss/sign_up.scss',
            'cr_internal_website_theme/static/src/scss/common.scss',
            'cr_internal_website_theme/static/src/scss/odoo_cloud_management.scss',
        ],
    },

    "installable": True,
    "application": False,
}
